site_name: Tech4Germany Archiv
extra_css: [css/extra.css]
repo_url: https://github.com/tech4germany/tech4germany.github.io
plugins:
  - search:
      min_search_length: 3
      lang: de

theme:
  name: material


  font:
    text: inter
  logo: Logo/Logo-t4g-00x109.png




